### ISSUE TITLE
Solidity ABI-based makeDealProposal

### ISSUE THREAD

**Issue by raulk** [lotus-web3/client-contract#13]
## Context

This method is a public-facing one. Having CBOR leak through here means that Ethereum clients like Hardhat, Foundry, etc. will need to encode CBOR, which unfortunately isn't very developer friendly.

## Ask

Decouple the user-facing API of this method (makeDealProposal) from the Filecoin-facing API, so that its parameter is a Solidity struct type, then conduct the CBOR transformation in code. This type is largerly based off filecoin-solidity's `DealProposal` type:

https://github.com/Zondax/filecoin-solidity/blob/24b1ec6737f6cdfc757909ac34a324be64657ef4/contracts/v0.8/types/MarketTypes.sol#L102-L114

Except that:

- Remove `client` field. This field should be populated by the contract by using the new `FilAddress::fromEthAddress()` constructor, giving it `self.address`.
- Add a `location_ref` field (confirm name with Aadi and Shrenuj) of string type.

Everything else can be be mapped directly.

## Notes

- I'm not sure what the `version` and `params` fields are doing. Worth asking Shrenuj.

**Comment by snissn** [comment]
I think that we want the client to exist, but we don't want the provider to exist, because that makes sense from a usability perspective - the client wants their data stored, and providers will accept the deal proposals. Also the code itself has provider commented out. Thirdly the example in slack:

```
./datadaotool submit-deal \
  --contract=-- \
  --commp=-- \
  --piece-size=262144 \
  --car-size=236445 \
  --start-epoch=144482 \
  --storage-price=0 \
  --payload-cid=-- \
  --client=t410fz--fj4i7i \
  --skip-ipni-announce=true \
  --location_ref=http://--/screenshot.car
```

specifies a client but no provider

**Comment by snissn** [comment]
also https://github.com/nonsense/datadaotool/blob/7a701221bf58843fe218092b1626b0d6890b26aa/types/types.go#L23

**Comment by raulk** [comment]
The client is the contract itself. The contract can populate its own address. The provider should be optional. If the user sets it, they may direct their deal to a single provider. If not, the contract could generate it on getDealProposal. But we haven't figured that one yet because it requires the SP to pass the right from address in eth_call.

**Comment by shrenujbansal** [comment]
Addressed when porting the client contract back to this repo
