### ISSUE TITLE
Enhance client contract

### ISSUE THREAD

**Issue by jennijuju** [lotus-web3/client-contract#8]
- [x] AuthenticateMessage needs to be read only with https://github.com/filecoin-project/builtin-actors/issues/1140
- [x] implement market notify hook
- [x] CBOR parsing for all deal proposal fields
- [x] add AddBalance to be able to  add escrow funds to the storage market,.
- [x] add WithdrawBalance to be able to withdraw balance from the market.
- [ ] add extendtermmax for data cap extension

**Comment by shrenujbansal** [comment]
Closing this and extracting last bullet into its own issue
